[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "/videos/*"
  [headers.values]
    cache-control = "max-age=31536000"
    Accept-Ranges = "bytes"
    Content-Type = "video/mp4"

[[headers]]
  for = "*.mp4"
  [headers.values]
    cache-control = "max-age=31536000"
    Accept-Ranges = "bytes"
    Content-Type = "video/mp4"